### ISSUE TITLE
How does your Dispatcher (Rx.Subject) manage dependencies?

### ISSUE THREAD

**Issue by kahlil** [rangle/ngcourse-next#26]
In classic Flux, the Dispatcher can manage dependencies between Actions. That is especially interesting in larger apps. How would you solve that with the Rx.Subject?

**Comment by igor-ka** [comment]
So the direction we are trying to take this is to reduce the number of situations where you do have to deal with dependencies between Actions, one way to achieve that is to structure you domain correctly. 

On the other end, when we have to deal with what we call "temporal dependencies" between stores, we prefer to use the facilities available with RxJS to orchestrate the streams that our stores expose.

Depending on the size of this "orchestration" logic, we think that it can be put into your "top level components" (which will pass this data down the component hierarchy) or in case of large apps, we can create a separate layer that deals with that (something that can be though of as stateless store that deals with orchestration of other stores, the name is up for grabs).

Otherwise, this approach has worked really well for us on different sizes of client project.

**Comment by kahlil** [comment]
@igor-ka very interesting! Thanks.
